# Generated by Django 3.1 on 2020-08-05 15:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('address', models.EmailField(max_length=255)),
                ('text', models.TextField()),
                ('delay', models.PositiveIntegerField()),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
